knplabs_translator_get:
    pattern:  /
    defaults: 
        _controller: knplabs_translator.controller.translator:getAction
    requirements: { _method: GET }

knplabs_translator_put:
    pattern:  /
    defaults: 
        _controller: knplabs_translator.controller.translator:postAction
        basura: null
    #requirements: { _method: POST }

