knplabs_translator_get:
    pattern:  /
    defaults: 
        _controller: knplabs_translator.controller.translator:getAction
    requirements: { _method: GET }

knplabs_translator_put:
    pattern:  /{basura}
    defaults: 
        _controller: knplabs_translator.controller.translator:putAction
        basura: null
    requirements: { _method: PUT }

